---
- name: Install Terraform on Jenkins Server
  hosts: jenkins_server # A host defined in your Ansible Inventory
  become: yes
  tasks:
    - name: Check if Terraform is installed
      command: terraform version
      ignore_errors: yes
      register: terraform_check

    - name: Install un-zip (a prerequisite)
      apt:
        name: unzip
        state: present
      when: terraform_check.rc != 0

    - name: Download Terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root
      when: terraform_check.rc != 0
      # COMMENT: This task ensures the Terraform binary is available for Jenkins to use.
